spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        #format_sql: true
  data:
    web:
      pageable:
        default-page-size: 10 #default = 20
        max-page-size: 2000
#        one-indexed-parameters: true #넘어온 page를 page-1 해서 쓴다 -> page가 1부터 동작하는 것 처럼 보임
logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.type: trace